### ISSUE TITLE
Medals not appearing

### ISSUE THREAD

**Issue by gabriel-a-oliver** [Husky-Game-Studio/Freight-Hopper#116]

**Comment by AJ213** [comment]
but reopen if still bork

**Comment by AJ213** [comment]
fug

**Comment by AJ213** [comment]
I believe the issue is not allowing enough time to send requests to steam to update our save data. This should maybe not be scene dependent

**Comment by AJ213** [comment]
I still have not had this happen to me after clearing my save data. I think this is only from restarting leaderboards

**Comment by AJ213** [comment]
should be fixed fr in 61f1d109c6fbb850c707ccf1564fd76095b8917f
