### ISSUE TITLE
Errors When Steam is not On

### ISSUE THREAD

**Issue by DilanMac** [Husky-Game-Studio/Freight-Hopper#88]
Going to add a large pile of if checks for now, but things like leaderboard will probably need something different to handle this

**Comment by DilanMac** [comment]
Steam API should now be off, but Level Complete no longer works

**Comment by AJ213** [comment]
I may have helped that a bit, but another issue is I keep seeing a debug log for "No Steam Detected, cannont send packets" but steam is clearly detected as its saying I am playing freight hopper. Not sure if this is some leftover debug log
