### ISSUE TITLE
Cloud Save Cache Thingy

### ISSUE THREAD

**Issue by AJ213** [Husky-Game-Studio/Freight-Hopper#91]
For tracking achievements, basically the replacement for all the file stuff we are doing currently as it contains all of the versioned level data like medals, best times, robertos... Well robertos is unversioned levels unless we like... want that.

Will require cloud save integration

**Comment by DilanMac** [comment]
No longer steam API cloud save, will instead use Steam Cloud Automerge, which is not too hard to set up.

**Comment by DilanMac** [comment]
For replay system, UploadScore comes with an int array, so the replay data will have to be formatted accordingly.

**Comment by AJ213** [comment]
Finished everything, including caching best time grabbing too. Just need file sync @DilanMac

**Comment by AJ213** [comment]
done and tested, just need to remember to make it public
